apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmyshow
  namespace: narasimha
  labels:
    app: bookmyshow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookmyshow
  template:
    metadata:
      labels:
        app: bookmyshow
    spec:
      containers:
        - name: bookmyshow
          image: narasimha0001/bookmyshow1:latest
          ports:
            - containerPort: 80
