apiVersion: v1
kind: Service
metadata:
  name: bookmyshow-service
spec:
  selector:
    app: bookmyshow
  ports:
    - protocol: TCP
      port: 80           # Exposed externally
      targetPort: 3000   # Maps to containerPort
  type: LoadBalancer     # ✅ For cloud (AWS, GCP, Azure); use NodePort if on Minikube
